### ISSUE TITLE
插件加载失败

### ISSUE THREAD

**Issue by NathanSummer** [KarisAya/nonebot_plugin_kawaii_robot#11]
01-01 22:19:18 [ERROR] nonebot | Failed to import "nonebot_plugin_kawaii_robot"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\NathanSummer\lemon\bot.py", line 25, in <module>
    nonebot.load_plugin('nonebot_plugin_kawaii_robot')
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot_plugin_kawaii_robot\__init__.py", line 17, in <module>
    from .utils import (
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot_plugin_kawaii_robot\utils.py", line 17, in <module>
    Bot_NICKNAME: str = list(nonebot.get_driver().config.nickname)[4]      # bot的nickname,可以换成你自己的
IndexError: list index out of range

**Comment by NathanSummer** [comment]
我的机器人是配置在prod里面，然后也设置了Bot_NICKNAME和Master_NICKNAME（几个字符串）但是加载不出来插件

**Comment by NathanSummer** [comment]
求大佬帮忙解答一下

**Comment by NachoNeko-daisuki** [comment]
> 我的机器人是配置在prod里面，然后也设置了Bot_NICKNAME和Master_NICKNAME（几个字符串）但是加载不出来插件

bot昵称的配置项是`NICKNAME=["昵称"]`，没有Master_NICKNAME项，你要配置的应该是`SUPERUSERS=["QQ号"]`

**Comment by NathanSummer** [comment]
> bot昵称的配置项是`NICKNAME=["昵称"]`，没有Master_NICKNAME项，你要配置的应该是`SUPERUSERS=["QQ号"]`

这个我知道，我没有动它，可是nonebot_plugin_kawaii_robot/utils.py的line17和line18是Bot_NICKNAME和Master_NICKNAME啊，而且原来的那个插件的配置信息介绍里面也说要配置这两项啊

**Comment by NathanSummer** [comment]
> 这个我知道，我没有动它，可是nonebot_plugin_kawaii_robot/utils.py的line17和line18是Bot_NICKNAME和Master_NICKNAME啊，而且原来的那个插件的配置信息介绍里面也说要配置这两项啊

[https://github.com/Special-Week/nonebot_plugin_smart_reply](url)里面的.env配置项config那一列

**Comment by NachoNeko-daisuki** [comment]
> > bot昵称的配置项是`NICKNAME=["昵称"]`，没有Master_NICKNAME项，你要配置的应该是`SUPERUSERS=["QQ号"]`
> 
> 这个我知道，我没有动它，可是nonebot_plugin_kawaii_robot/utils.py的line17和line18是Bot_NICKNAME和Master_NICKNAME啊，而且原来的那个插件的配置信息介绍里面也说要配置这两项啊

首先如果你有仔细查看两个插件的代码会发现本插件的bot_master获取的是env中的superuser而不是nonebot_plugin_smart_reply那样的自定义昵称。
其次你说bot_nickname我第一反应认为你是配置项写错了，看了一遍日志发现你报错的原因是你把[utils.py](https://github.com/KarisAya/nonebot_plugin_kawaii_robot/blob/master/utils.py)line17`Bot_NICKNAME: str = list(nonebot.get_driver().config.nickname)[0] `改成了`Bot_NICKNAME: str = list(nonebot.get_driver().config.nickname)[4] `，而你env里nickname的list长度没有4

**Comment by NathanSummer** [comment]
> 首先如果你有仔细查看两个插件的代码会发现本插件的bot_master获取的是env中的superuser而不是nonebot_plugin_smart_reply那样的自定义昵称。 其次你说bot_nickname我第一反应认为你是配置项写错了，看了一遍日志发现你报错的原因是你把[utils.py](https://github.com/KarisAya/nonebot_plugin_kawaii_robot/blob/master/utils.py)line17`Bot_NICKNAME: str = list(nonebot.get_driver().config.nickname)[0] `改成了`Bot_NICKNAME: str = list(nonebot.get_driver().config.nickname)[4] `，而你env里nickname的list长度没有4

啊啊这，我确实没有仔细查看过两插件代码让您见笑了，我本来也没有添那两条NICKNAME，也没有改那个中括号里面的数字，全部都是原封不动的（后来改成4是因为我BOT的nickname有四个字符串），而且superuser也一直都是我QQ号。可它当时运行报的错和现在好像是一模一样
的，要不是它报错我也不会去看另一个插件更不会改那个数字呀，所以您的意思是把两个数字都改成1还是？

**Comment by NachoNeko-daisuki** [comment]
> > 首先如果你有仔细查看两个插件的代码会发现本插件的bot_master获取的是env中的superuser而不是nonebot_plugin_smart_reply那样的自定义昵称。 其次你说bot_nickname我第一反应认为你是配置项写错了，看了一遍日志发现你报错的原因是你把[utils.py](https://github.com/KarisAya/nonebot_plugin_kawaii_robot/blob/master/utils.py)line17`Bot_NICKNAME: str = list(nonebot.get_driver().config.nickname)[0] `改成了`Bot_NICKNAME: str = list(nonebot.get_driver().config.nickname)[4] `，而你env里nickname的list长度没有4
> 
> 啊啊这，我确实没有仔细查看过两插件代码让您见笑了，我本来也没有添那两条NICKNAME，也没有改那个中括号里面的数字，全部都是原封不动的（后来改成4是因为我BOT的nickname有四个字符串），而且superuser也一直都是我QQ号。可它当时运行报的错和现在好像是一模一样 的，要不是它报错我也不会去看另一个插件更不会改那个数字呀，所以您的意思是怎样改正可以正常运行呢？
> 
> 真的很抱歉麻烦您了！！！ /鞠躬 /鞠躬 /鞠躬

数字为0获取的是你配置的nickname中的第一个昵称，相同报错就是和 #6 一样，看看.env里是不是`ENVIRONMENT=prod`

**Comment by NathanSummer** [comment]
现在的配置：
.env
ENVIRONMENT=prod
.env.prod
SUPERUSER=["**********"] # 超级用户 （QQ号）
NICKNAME=["**"] # 机器人名字（昵称）
utils.py
Bot_NICKNAME: str = list(nonebot.get_driver().config.nickname)[0]      # bot的nickname,可以换成你自己的
Bot_MASTER: str = list(nonebot.get_driver().config.superusers)[0]      # bot的主人名称,也可以换成你自己的

现在的报错：
01-02 10:14:03 [ERROR] nonebot | Failed to import "nonebot_plugin_kawaii_robot"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\NathanSummer\lemon\bot.py", line 25, in <module>
    nonebot.load_plugin('nonebot_plugin_kawaii_robot')
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot_plugin_kawaii_robot\__init__.py", line 17, in <module>
    from .utils import (
  File "C:\Users\NathanSummer\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot_plugin_kawaii_robot\utils.py", line 18, in <module>
    Bot_MASTER: str = list(nonebot.get_driver().config.superusers)[0]      # bot的主人名称,也可以换成你自己的
IndexError: list index out of range

请大佬指正😭😭😭

**Comment by KarisAya** [comment]
18行
https://github.com/KarisAya/nonebot_plugin_kawaii_robot/blob/master/utils.py#L18
这个根本没有用到，是一段无效代码。
发报错的话最好发截图这样太乱了

**Comment by NathanSummer** [comment]
> 18行 https://github.com/KarisAya/nonebot_plugin_kawaii_robot/blob/master/utils.py#L18 这个根本没有用到，是一段无效代码。 发报错的话最好发截图这样太乱了

是说要把第18行删了还是？

**Comment by NathanSummer** [comment]
![image](https://user-images.githubusercontent.com/88868171/210191692-d6aff3b1-02ca-420c-bbb9-e69c79b999eb.png)
上面提到的报错

**Comment by KarisAya** [comment]
> ![image](https://user-images.githubusercontent.com/88868171/210191692-d6aff3b1-02ca-420c-bbb9-e69c79b999eb.png) 上面提到的报错

这个报错的原因就是没有配置超管，这插件没有用到超管但是一般没有不配置超管的所以我没管他。
如果你配置了超管那有可能是配置的问题。

**Comment by KarisAya** [comment]
> ![image](https://user-images.githubusercontent.com/88868171/210191692-d6aff3b1-02ca-420c-bbb9-e69c79b999eb.png) 上面提到的报错

你找到你的.env.prod 用电脑自带的记事本打开，看看里面是什么样的

**Comment by NathanSummer** [comment]
> 你找到你的.env.prod 用电脑自带的记事本打开，看看里面是什么样的

额...是这样的？
![image](https://user-images.githubusercontent.com/88868171/210191952-7b8936a0-f034-4f85-b4f6-ed3cee3d86a7.png)

**Comment by KarisAya** [comment]
配置的没问题，但不知道为什么没加载出来。你确定.env里面 ENVIRONMENT=prod 吗。
要不然把第十八行删掉试试看。

你其他需要超管权限的插件能用吗

**Comment by NathanSummer** [comment]
![image](https://user-images.githubusercontent.com/88868171/210192301-464db177-9a66-4c7c-82bf-33c64ecc8a51.png)
确实设置的是prod
反闪照的插件是只有超管可以指令实时修改全局配置
它是可以用的
删去line18的结果是酱紫的喔...↓
![image](https://user-images.githubusercontent.com/88868171/210192462-c19e413c-974b-4161-9981-cb679c0911a3.png)

**Comment by KarisAya** [comment]
.env.prod关于这个插件的配置全删掉试一试

**Comment by NathanSummer** [comment]
> .env.prod关于这个插件的配置全删掉试一试

这样就没有再报错了欸！！

**Comment by NathanSummer** [comment]
> .env.prod关于这个插件的配置全删掉试一试

那我修改配置就在config.py里面咯？

**Comment by NachoNeko-daisuki** [comment]
> ![image](https://user-images.githubusercontent.com/88868171/210192301-464db177-9a66-4c7c-82bf-33c64ecc8a51.png) 确实设置的是prod 反闪照的插件是只有超管可以指令实时修改全局配置 它是可以用的 删去line18的结果是酱紫的喔...↓ ![image](https://user-images.githubusercontent.com/88868171/210192462-c19e413c-974b-4161-9981-cb679c0911a3.png)

你的leaf_ignore项把单引号改用双引号试试`LEAF_IGNORE= ["/", "."]`
