### ISSUE TITLE
插件加载失败, 获取不到nickname?

### ISSUE THREAD

**Issue by KiDisplayBlueScreen** [KarisAya/nonebot_plugin_kawaii_robot#6]
12-14 14:27:46 [ERROR] nonebot | Failed to import "nonebot_plugin_kawaii_robot"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Program Files (x86)\nb\QQbot\.\bot.py", line 40, in <module>
    nonebot.load_plugin('nonebot_plugin_kawaii_robot')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_kawaii_robot\__init__.py", line 15, in <module>
    from .utils import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_kawaii_robot\utils.py", line 16, in <module>
    Bot_NICKNAME: str = list(nonebot.get_driver().config.nickname)[0]      # bot的nickname,可以换成你自己的
IndexError: list index out of range
是从.env.prod里获取nickname吗? 我已经配置了啊

**Comment by KarisAya** [comment]
这是因为nonebot.get_driver().config.nickname长度为0才会这样报错，也就是没有配置nickname

**Comment by KiDisplayBlueScreen** [comment]
> 这是因为nonebot.get_driver().config.nickname长度为0才会这样报错，也就是没有配置nickname
哪里配置 .env.prod吗

**Comment by KarisAya** [comment]
> 

在.env里面看你的机器人用的是哪个配置

**Comment by KiDisplayBlueScreen** [comment]
> > 
> 
> 在.env里面看你的机器人用的是哪个配置
哦 现在可以加载了 但是没反应
12-16 10:27:02 [INFO] nonebot_plugin_gocqhttp | 收到群  内  的消息: mua (-2142509073)
12-16 10:27:02 [SUCCESS] nonebot | OneBot V11  | [message.group.normal]: Message -2142509073 from  "mua"
12-16 10:27:02 [DEBUG] nonebot | Checking for matchers in priority 0...
12-16 10:27:02 [DEBUG] nonebot | Checking for matchers in priority 1...
12-16 10:27:02 [DEBUG] nonebot | Checking for matchers in priority 5...
12-16 10:27:02 [DEBUG] nonebot | Checking for matchers in priority 10...
12-16 10:27:02 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_kawaii_robot)
12-16 10:27:02 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_kawaii_robot)
12-16 10:27:02 [DEBUG] nonebot | Running handler Dependent(call=_)
12-16 10:27:02 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_kawaii_robot) running complete
插件已经接收到消息但是没有回复?其他插件正常

**Comment by KiDisplayBlueScreen** [comment]
> > 
> 
> 在.env里面看你的机器人用的是哪个配置
好的 顺便问问能不能设置为不需要@也能回复

**Comment by NathanSummer** [comment]
> 这是因为nonebot.get_driver().config.nickname长度为0才会这样报错，也就是没有配置nickname

Bot_NICKNAME和Bot_Master怎么配置

**Comment by lgc2333** [comment]
可以close了
